# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2020-01-15 18:12
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ievv_api_key', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthenticationLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_data', django.contrib.postgres.fields.jsonb.JSONField(default=dict, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='scopedapikey',
            name='authentication_log',
        ),
        migrations.AddField(
            model_name='authenticationlog',
            name='api_key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ievv_api_key.ScopedAPIKey'),
        ),
    ]
